// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */
import { css } from 'lit';

export default css`
	/* stylelint-disable */
  :host {
    display: contents;

    /* For better DX, we'll reset the margin here so the base part can inherit it */
    margin: 0;
  }

  .alert {
    position: relative;
    display: flex;
    align-items: stretch;
    background-color: var(--syn-panel-background-color);
    border: solid var(--syn-panel-border-width) var(--syn-panel-border-color);
    border-top-width: calc(var(--syn-panel-border-width) * 3);
    border-radius: var(--syn-border-radius-medium);
    font-family: var(--syn-font-sans);
    font-size: var(--syn-font-size-small);
    font-weight: var(--syn-font-weight-normal);
    line-height: 1.6;
    color: var(--syn-color-neutral-700);
    margin: inherit;
  }

  .alert:not(.alert--has-icon) .alert__icon,
  .alert:not(.alert--closable) .alert__close-button {
    display: none;
  }

  .alert__icon {
    flex: 0 0 auto;
    display: flex;
    align-items: center;
    font-size: var(--syn-font-size-large);
    padding-inline-start: var(--syn-spacing-large);
  }

  .alert--primary {
    border-top-color: var(--syn-color-primary-600);
  }

  .alert--primary .alert__icon {
    color: var(--syn-color-primary-600);
  }

  .alert--success {
    border-top-color: var(--syn-color-success-600);
  }

  .alert--success .alert__icon {
    color: var(--syn-color-success-600);
  }

  .alert--neutral {
    border-top-color: var(--syn-color-neutral-600);
  }

  .alert--neutral .alert__icon {
    color: var(--syn-color-neutral-600);
  }

  .alert--warning {
    border-top-color: var(--syn-color-warning-600);
  }

  .alert--warning .alert__icon {
    color: var(--syn-color-warning-600);
  }

  .alert--danger {
    border-top-color: var(--syn-color-danger-600);
  }

  .alert--danger .alert__icon {
    color: var(--syn-color-danger-600);
  }

  .alert__message {
    flex: 1 1 auto;
    display: block;
    padding: var(--syn-spacing-large);
    overflow: hidden;
  }

  .alert__close-button {
    flex: 0 0 auto;
    display: flex;
    align-items: center;
    font-size: var(--syn-font-size-medium);
    padding-inline-end: var(--syn-spacing-medium);
  }
`;
