packages:
  - "packages/*"
  - "packages/_private/*"
# Needed because of following issue: https://github.com/microsoft/vscode-eslint/issues/1986#issuecomment-2799868163
publicHoistPattern:
  - "*eslint*" # this seems to be needed as long as we are using eslint v8

# Make sure that we only allow updates of packages that have been released for at least 24 hours
minimumReleaseAge: 1440
