packages:
  - "packages/*"
  - "packages/_private/*"

# This is a workaround for pnpm as eslint deps are not hoisted anymore,
# which causes issues with the VSCode ESLint extension.
# @see https://github.com/microsoft/vscode-eslint/issues/1986#issuecomment-2799868163
publicHoistPattern:
  - "*eslint*"
