// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */
import SynDialog from './dialog.component.js';

export * from './dialog.component.js';
export default SynDialog;

SynDialog.define('syn-dialog');

declare global {
  interface HTMLElementTagNameMap {
    'syn-dialog': SynDialog;
  }
}
