import type { IntentDefinition } from '../../types.js';

export const inputIntents: IntentDefinition[] = [
  {
    category: 'input',
    description: 'Use when a user should provide short, single-line text input.',
    id: 'input.text.short',
    userGoal: 'Capture compact textual values in a form field.',
  },
  {
    category: 'input',
    description: 'Use when a user should provide an email address in a format-aware field.',
    id: 'input.text.email',
    userGoal: 'Enter a valid email address with appropriate keyboard and validation behavior.',
  },
  {
    category: 'input',
    description: 'Use when a user should provide a telephone number.',
    id: 'input.text.telephone',
    userGoal: 'Enter a contact phone number with telephone-optimized keyboard behavior.',
  },
  {
    category: 'input',
    description: 'Use when a user should provide a URL or web address.',
    id: 'input.text.url',
    userGoal: 'Enter a valid web address with URL-optimized keyboard behavior.',
  },
  {
    category: 'input',
    description: 'Use when a user should provide searchable text for filtering or querying.',
    id: 'input.text.search',
    userGoal: 'Enter and refine search terms quickly in a dedicated search field.',
  },
  {
    category: 'input',
    description: 'Use when a user should enter confidential text that must be masked, such as a password.',
    id: 'input.text.secret',
    userGoal: 'Enter sensitive text securely with masked characters and optional reveal behavior.',
  },
  {
    category: 'input',
    description: 'Use when a user should enter a numeric value directly in a form field.',
    id: 'input.number.field',
    userGoal: 'Type or adjust an exact numeric value with keyboard-friendly controls.',
  },
  {
    category: 'input',
    description: 'Use when a user should provide longer, multi-line input.',
    id: 'input.text.long',
    userGoal: 'Capture detailed comments, descriptions, or narrative responses.',
  },
  {
    category: 'input',
    description: 'Use when one option should be selected from predefined choices.',
    id: 'input.selection.single',
    userGoal: 'Make one explicit selection from a known set.',
  },
  {
    category: 'input',
    description: 'Use when multiple options should be selected from predefined choices.',
    id: 'input.selection.multiple',
    userGoal: 'Select multiple relevant options in one control.',
  },
  {
    category: 'input',
    description: 'Use when options are numerous and should be filtered by typing.',
    id: 'input.selection.searchable',
    userGoal: 'Find and select options quickly through live filtering.',
  },
  {
    category: 'input',
    description: 'Use when multiple options should be selected from a filterable list.',
    id: 'input.selection.searchable.multiple',
    userGoal: 'Find and select multiple options quickly through live filtering.',
  },
  {
    category: 'input',
    description: 'Use for binary choices that apply immediately on toggle.',
    id: 'input.binary.immediate',
    userGoal: 'Enable or disable a setting with instant effect.',
  },
  {
    category: 'input',
    description: 'Use for binary choices that are submitted later with the form.',
    id: 'input.binary.deferred',
    userGoal: 'Record a binary preference without immediate side effects.',
  },
  {
    category: 'input',
    description: 'Use when files or folders must be attached or uploaded.',
    id: 'input.file.upload',
    userGoal: 'Provide one or more local files for processing.',
  },
  {
    category: 'input',
    description: 'Use when a user should select one numeric value within a bounded range, where quick adjustment matters more than exact precision.',
    id: 'input.number.range',
    userGoal: 'Pick a numeric value quickly with immediate visual feedback across a range.',
  },
  {
    category: 'input',
    description: 'Use when a user should select lower and upper numeric bounds within a bounded range, where quick adjustment matters more than exact precision.',
    id: 'input.number.range.interval',
    userGoal: 'Pick lower and upper bounds quickly with immediate visual feedback across a range.',
  },
  {
    category: 'input',
    description: 'Use when a user should pick a calendar date.',
    id: 'input.date.day',
    userGoal: 'Select or type a specific day with date-aware validation and picker support.',
  },
  {
    category: 'input',
    description: 'Use when a user should pick a time of day.',
    id: 'input.date.time',
    userGoal: 'Select or type a specific time with time-aware validation and picker support.',
  },
  {
    category: 'input',
    description: 'Use when a user should pick both date and time together in one field.',
    id: 'input.date.datetime-local',
    userGoal: 'Select or type a local date-time value with combined date and time controls.',
  },
  {
    category: 'input',
    description: 'Use grouped options to organize long option lists into logical clusters.',
    id: 'input.selection.grouped-options',
    userGoal: 'Find and choose options faster through labeled option groupings.',
  },
  {
    category: 'input',
    description: 'Use when related checkbox or switch controls should be grouped under a shared label and optional help text.',
    id: 'input.grouping.checkbox',
    userGoal: 'Understand and complete related checkboxes or switches as one coherent section.',
  },
  {
    category: 'input',
    description: 'Use when related form controls should be grouped under a shared legend and optional description.',
    id: 'input.grouping.fieldset',
    userGoal: 'Understand and complete related form fields as one coherent section.',
  },
];
