import fs from 'node:fs';
import { baselines } from '../config.js';

/**
 * Converts a version string to a valid export name
 *
 * @example
 * versionToExportName('3.0.0') // returns 'v3_0_0'
 *
 * @param {string} version The version string to convert (e.g., "3.0.0")
 * @returns {string} The export name for the given version
 */
const versionToExportName = version => `v${version.replace(/\./g, '_')}`;

/**
 * Generates an index file for all baselines in the baselines directory
 */
export const generateBaselineIndex = () => {
  if (!fs.existsSync(baselines)) {
    throw new Error(`Baselines directory not found at path: ${baselines}`);
  }

  // Get all files in the baselines directory
  // Don`t include the index file itself
  const files = fs
    .readdirSync(baselines)
    .filter(file => file.endsWith('.js') && file !== 'index.js');

  const exportsMap = files
    .map(file => `export { default as ${versionToExportName(file.replace('.js', ''))} } from './${file}';`)
    .join('\n');

  const content = `
/**
 * This file is auto-generated by the createBaseline function. Do not edit this file directly.
 * To update the baseline, run syn-create-baseline.js with the appropriate version to regenerate this file.
 */
${exportsMap}
`.trimStart();

  return fs.writeFileSync(`${baselines}/index.js`, content, 'utf-8');
};
