const AppShellSelectors = {
  appHeader: 'syn-header',
  appSideNav: 'syn-side-nav',

  // Regressions for #921
  header921NavItem: '#header921',
};

const AllComponentSelectors = {
  // Accordion
  accordionContent: '#tab-content-Accordion',
  accordionDetails: '#tab-content-Accordion syn-details',
  accordionLink: '#tab-Accordion',

  // Alert
  alertAll: '#tab-content-Alert syn-alert',
  alertContent: '#tab-content-Alert',
  alertLink: '#tab-Alert',

  // ButtonGroup
  buttonGroupContent: '#tab-content-ButtonGroup',
  buttonGroupLink: '#tab-ButtonGroup',

  // Combobox
  combobox626: '#tab-content-Combobox syn-combobox[data-testid="combobox-626"]',
  combobox626Async: '#tab-content-Combobox syn-combobox[data-testid="combobox-626-async"]',
  combobox627: '#tab-content-Combobox syn-combobox[data-testid="combobox-627-delimiter"]',
  combobox632: '#tab-content-Combobox syn-combobox[data-testid="combobox-632"]',
  combobox797: '#tab-content-Combobox syn-combobox[data-testid="combobox-797"]',
  combobox805MixedMulti: '#tab-content-Combobox syn-combobox[data-testid="combobox-805-multi"]',
  combobox805MixedSingle: '#tab-content-Combobox syn-combobox[data-testid="combobox-805-single"]',
  combobox813Form: '#tab-content-Combobox syn-combobox[data-testid="combobox-form-813"]',
  combobox813FormOptions: '#tab-content-Combobox syn-combobox[data-testid="combobox-form-813"] syn-option',
  combobox813Level: '#tab-content-Combobox syn-combobox[data-testid="combobox-level-813"]',
  combobox847Multiple: '#tab-content-Combobox syn-combobox[data-testid="combobox-847-multiple"]',
  combobox885ValueZeroNumber: '#tab-content-Combobox syn-combobox[data-testid="combobox-885-value-zero-number"]',
  combobox885ValueZeroString: '#tab-content-Combobox syn-combobox[data-testid="combobox-885-value-zero-string"]',
  combobox1036Delimiter: '#tab-content-Combobox syn-combobox[data-testid="combobox-1036-subsequently-changed-delimiter"]',
  combobox1056DelimiterAsyncPreValue: '#tab-content-Combobox syn-combobox[data-testid="combobox-1056-async-delimiter-change-with-async-pre-value"]',
  combobox1056DelimiterPreValue: '#tab-content-Combobox syn-combobox[data-testid="combobox-1056-async-delimiter-change-with-pre-value"]',
  comboboxContent: '#tab-content-Combobox',
  comboboxFormReset: '#tab-content-Combobox form syn-button',
  comboboxLink: '#tab-Combobox',
  comboboxReadonly: '#tab-content-Combobox syn-combobox[data-testid="combobox-1172-readonly-combobox"]',

  // Input
  input417NoValue: '#tab-content-Input syn-input[data-testid="input-417-numeric-no-value"]',
  input417NumericMinFractionDigitsModern: '#tab-content-Input syn-input[data-testid="input-838-numeric-modern-min-fraction-digits"]',
  input417NumericMinFractionDigitsNative: '#tab-content-Input syn-input[data-testid="input-838-numeric-native-min-fraction-digits"]',
  input417NumericModern: '#tab-content-Input syn-input[data-testid="input-417-numeric-modern"]',
  input417NumericNative: '#tab-content-Input syn-input[data-testid="input-417-numeric-native"]',
  input872SpinButtons: '#tab-content-Input syn-input[data-testid="input-872-spin-buttons"]',
  input1023Autocorrect: '#tab-content-Input syn-input[data-testid="input-1023-autocorrect"]',
  inputContent: '#tab-content-Input',
  inputLink: '#tab-Input',

  // NgModelUpdateOn
  ngModelUpdateOnCheckbox: '#tab-content-NgModelUpdateOn syn-checkbox[data-testid="checkbox-808"]',
  ngModelUpdateOnCheckboxChanged: '#tab-content-NgModelUpdateOn syn-checkbox[data-testid="checkbox-changed-808"]',
  ngModelUpdateOnCheckboxResult: '#tab-content-NgModelUpdateOn [data-testid="result-checkbox-808"]',
  ngModelUpdateOnContent: '#tab-content-NgModelUpdateOn',
  ngModelUpdateOnInput: '#tab-content-NgModelUpdateOn syn-input[data-testid="input-808"]',
  ngModelUpdateOnInputChanged: '#tab-content-NgModelUpdateOn syn-input[data-testid="input-changed-808"]',
  ngModelUpdateOnInputResult: '#tab-content-NgModelUpdateOn [data-testid="result-input-808"]',
  ngModelUpdateOnLink: '#tab-NgModelUpdateOn',
  ngModelUpdateOnRange: '#tab-content-NgModelUpdateOn syn-range[data-testid="range-808"]',
  ngModelUpdateOnRangeChanged: '#tab-content-NgModelUpdateOn syn-range[data-testid="range-changed-808"]',
  ngModelUpdateOnRangeResult: '#tab-content-NgModelUpdateOn [data-testid="result-range-808"]',

  // Optgroup
  optgroupFirstEnabledItems: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(1) syn-option:not([disabled])',
  optgroupFirstItem: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(1)',
  optgroupLink: '#tab-OptGroup',
  optgroupSecondEnabledItems: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(2) syn-option:not([disabled])',
  optgroupSecondItem: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(2)',
  optgroupThirdEnabledItems: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(3) syn-option:not([disabled])',
  optgroupThirdItem: '#tab-content-OptGroup syn-select syn-optgroup:nth-of-type(3)',

  // Select
  select847Multiple: '#tab-content-Select syn-select[data-testid="select-847-multiple"]',
  select885ValueZeroNumber: '#tab-content-Select syn-select[data-testid="select-885-value-zero-number"]',
  select885ValueZeroString: '#tab-content-Select syn-select[data-testid="select-885-value-zero-string"]',
  select1036Delimiter: '#tab-content-Select syn-select[data-testid="select-1036-subsequently-changed-delimiter"]',
  select1056DelimiterAsyncPreValue: '#tab-content-Select syn-select[data-testid="select-1056-async-delimiter-change-with-async-pre-value"]',
  select1056DelimiterPreValue: '#tab-content-Select syn-select[data-testid="select-1056-async-delimiter-change-with-pre-value"]',
  selectContent: '#tab-content-Select',
  selectForm: '#tab-content-Select syn-select[data-testid="select-form-813"]',
  selectFormOptions: '#tab-content-Select syn-select[data-testid="select-form-813"] syn-option',
  selectFormReset: '#tab-content-Select form syn-button',
  selectLevel: '#tab-content-Select syn-select[data-testid="select-level-813"]',
  selectLink: '#tab-Select',
  selectMixedIdMultiSelect: '#tab-content-Select syn-select[data-testid="select-805-multi-select"]',
  selectMixedIdSingleSelect: '#tab-content-Select syn-select[data-testid="select-805-single-select"]',
  selectReadonly: '#tab-content-Select syn-select[data-testid="select-1177-readonly-select"]',
  selectWithDelimiter: '#tab-content-Select syn-select[data-testid="select-540-delimiter"]',

  // Tabgroup
  tabGroupAdded: '#tab-content-TabGroup syn-tab:nth-of-type(5)',
  tabGroupAddedPanel: '#tab-content-TabGroup syn-tab-panel:nth-of-type(5)',
  tabGroupAddTabButton: '#tab-content-TabGroup syn-button',
  tabGroupAdvanced: '#tab-content-TabGroup syn-tab:nth-of-type(4)',
  tabGroupAdvancedPanel: '#tab-content-TabGroup syn-tab-panel:nth-of-type(4)',
  tabGroupCustom: '#tab-content-TabGroup syn-tab:nth-of-type(3)',
  tabGroupGeneral: '#tab-content-TabGroup syn-tab:nth-of-type(1)',
  tabGroupLink: '#tab-TabGroup',

  // Validate

  // #851 syn-validate in dynamic tabs
  validate851AddTabButton: '#tab-content-Demo851SynValidateInDynamicTabs syn-button[data-testid="validate851-add-tab-button"]',
  validate851Content: '#tab-content-Demo851SynValidateInDynamicTabs',
  validate851Link: '#tab-Demo851SynValidateInDynamicTabs',
  validate851Select1: '#tab-content-Demo851SynValidateInDynamicTabs syn-select[data-testid="validate851-select-1"]',
  validate851Select2: '#tab-content-Demo851SynValidateInDynamicTabs syn-select[data-testid="validate851-select-2"]',
  validate851Select3: '#tab-content-Demo851SynValidateInDynamicTabs syn-select[data-testid="validate851-select-3"]',
  validate851Select4: '#tab-content-Demo851SynValidateInDynamicTabs syn-select[data-testid="validate851-select-4"]',
  validate851Tab1: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab[data-testid="validate851-tab-1"]',
  validate851Tab2: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab[data-testid="validate851-tab-2"]',
  validate851Tab3: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab[data-testid="validate851-tab-3"]',
  validate851TabGroup: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab-group[data-testid="validate851-tab-group"]',
  validate851TabPanel1: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab-panel[data-testid="validate851-tab-panel-1"]',
  validate851TabPanel2: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab-panel[data-testid="validate851-tab-panel-2"]',
  validate851TabPanel3: '#tab-content-Demo851SynValidateInDynamicTabs syn-tab-panel[data-testid="validate851-tab-panel-3"]',
  validate851Validate1: '#tab-content-Demo851SynValidateInDynamicTabs syn-validate[data-testid="validate851-validate-1"]',
  validate851Validate2: '#tab-content-Demo851SynValidateInDynamicTabs syn-validate[data-testid="validate851-validate-2"]',
  validate851Validate3: '#tab-content-Demo851SynValidateInDynamicTabs syn-validate[data-testid="validate851-validate-3"]',

  validate915: '#tab-content-Validate syn-validate[data-testid="validate-915"]',
  validateContent: '#tab-content-Validate',
  validateLink: '#tab-Validate',
};

export default {
  ...AllComponentSelectors,
  ...AppShellSelectors,
  addInfoLoc: '#additional-info',
  angular: 'syn-option[value=angular]',
  birth: '#input-date',
  donations: '#donations',
  emailLoc: '#input-email',
  experienceLittle: '#experience-little',
  experienceLoc: '#experience',
  formLoc: 'form',
  formStatus: 'syn-alert.form-validation-message',
  frontend: '#select-role  syn-option[value=frontend]',
  genderLoc: '#radiogroup-gender',
  happinessLoc: '#happiness',
  nameLoc: '#input-text',
  nationalityLoc: '#input-nationality',
  newsLocBeta: '#checkbox-newsletter-beta',
  newsLocSyn: '#checkbox-newsletter-default',
  newsLocSynNg: '#checkbox-newsletter-angular',
  newsLocSynReact: '#checkbox-newsletter-react',
  newsLocSynVue: '#checkbox-newsletter-vue',
  newsLocUI: '#checkbox-newsletter-ui',
  newsLocUX: '#checkbox-newsletter-ux',
  newsLocVanilla: '#checkbox-newsletter-vanilla',
  passLoc: '#input-password',
  passRecoveryLoc: '#input-number',
  phoneLoc: '#input-phone',
  preferredContactEmail: '#preferred-contact-method syn-radio-button[value=email]',
  preferredContactLoc: '#preferred-contact-method',
  previousNationalities: '#input-previous-nationality',
  previousRolesLoc: '#select-previous-roles',
  reset: '.syn-submit-buttons > syn-button:nth-child(1)',
  roleLoc: '#select-role',
  sizeToggleLarge: '.meta-navigation syn-icon-button[data-size=large]',
  sizeToggleMedium: '.meta-navigation syn-icon-button[data-size=medium]',
  sizeToggleSmall: '.meta-navigation syn-icon-button[data-size=small]',
  submit: '.syn-submit-buttons > syn-button:nth-child(2)',
  testingFrameworks: '#testing-frameworks',
  themeSwitch: '.meta-navigation syn-select',
  topicLoc: '#topics',
};
