import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { type CoreEntity } from '../schemas/core-entity.js';

/**
 * Build template metadata entities by scanning template layer files.
 * Templates don't have a separate collector (they're generated by storybook scraper).
 * This function discovers template entities from the examples layer and creates minimal metadata.
 */
export const createTemplateEntities = async (
  outputDir: string,
): Promise<CoreEntity[]> => {
  const templates: CoreEntity[] = [];

  try {
    const templateLayerDir = join(outputDir, 'layers', 'examples', 'template');
    const files = await readdir(templateLayerDir);

    // Find all template markdown files and create metadata entities
    files.forEach((file) => {
      if (!file.startsWith('template:') || !file.endsWith('.md')) {
        return;
      }

      const entityId = file.replace('.md', '');
      const templateName = entityId.replace('template:', '');

      const entity: CoreEntity = {
        custom: {},
        id: entityId,
        kind: 'template' as const,
        layers: {
          examples: [{
            layer: 'examples',
            path: `layers/examples/template/${file}`,
          }],
        },
        name: templateName
          .split('-')
          .map(word => word.charAt(0).toUpperCase() + word.slice(1))
          .join(' '),
        package: 'docs',
        relations: [],
        since: '1.0.0',
        sources: [],
        status: 'stable',
        tags: ['template'],
      };

      templates.push(entity);
    });
  } catch {
    // Template layer directory might not exist yet, which is fine
  }

  return templates;
};
