// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/angular wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
import {
  Component,
  ElementRef,
  NgZone,
  Input,
  Output,
  EventEmitter,
  AfterContentInit,
} from '@angular/core';
import type SynFieldset from '@synergy-design-system/components/components/fieldset/fieldset.component.js';

import '@synergy-design-system/components/components/fieldset/fieldset.js';

/**
 * @summary Fieldsets are used to group related elements in a form.
 * @documentation https://synergy-design-system.github.io/?path=/docs/components-syn-fieldset--docs
 * @status stable
 * @since 3.x.x
 *
 * @slot - The fieldset's main content. Place form controls inside the fieldset to group them together.
 * @slot legend - Add a legend to the fieldset. This is displayed as the title of the fieldset. Alternatively, you can use the `legend` attribute.
 * @slot description - Add a description to the fieldset. This is displayed below the legend and provides additional information about the fieldset. Alternatively, you can use the `description` attribute.
 *
 * @csspart base - The component's base wrapper.
 * @csspart legend - The component's legend element.
 * @csspart description - The component's description element.
 * @csspart field-container - The container for the fieldset's fields.
 *
 * @cssproperty --item-gap-normal - The gap between the fields in the fieldset when using normal layout. Defaults to `--syn-spacing-large`
 * @cssproperty --item-gap-dense - The gap between the fields in the fieldset when using dense layout. Defaults to `--syn-spacing-x-small`
 */
@Component({
  selector: 'syn-fieldset',
  standalone: true,
  template: '<ng-content></ng-content>',
})
export class SynFieldsetComponent {
  public nativeElement: SynFieldset;
  private _ngZone: NgZone;

  constructor(e: ElementRef, ngZone: NgZone) {
    this.nativeElement = e.nativeElement;
    this._ngZone = ngZone;
  }

  /**
* The legend for the fieldset.
* This is displayed as the title of the fieldset.
If not provided, the fieldset will not have a description.
 */
  @Input()
  set description(v: SynFieldset['description']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.description = v));
  }
  get description(): SynFieldset['description'] {
    return this.nativeElement.description;
  }

  /**
* The legend for the fieldset.
* This is displayed as the title of the fieldset.
If not provided, the fieldset will not have a legend.
 */
  @Input()
  set legend(v: SynFieldset['legend']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.legend = v));
  }
  get legend(): SynFieldset['legend'] {
    return this.nativeElement.legend;
  }

  /**
* Whether the fieldset is disabled.
When true, all form controls inside the fieldset are disabled
 */
  @Input()
  set disabled(v: '' | SynFieldset['disabled']) {
    this._ngZone.runOutsideAngular(
      () => (this.nativeElement.disabled = v === '' || v),
    );
  }
  get disabled(): SynFieldset['disabled'] {
    return this.nativeElement.disabled;
  }

  /**
* The layout of the fieldset.
* This determines how the fields are displayed.
Defaults to `one-column`.

- `one-column`: All fields are displayed in a single column.
- `two-columns`: Fields are displayed in two columns.
* Will automatically fall back to one-column if the fieldset is too narrow to display two columns.
 */
  @Input()
  set layout(v: SynFieldset['layout']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.layout = v));
  }
  get layout(): SynFieldset['layout'] {
    return this.nativeElement.layout;
  }

  /**
* The spacing between the fields in the fieldset.
* This can be set to `dense` or `normal`.
* Defaults to `normal`.
A dense layout is useful for displaying smaller form controls, e.g.
* checkboxes or radio buttons, while a normal layout is better suited for larger form controls, e.g.
* text inputs or selects.
The spacing can also be controlled with the `--item-gap-normal` and `--item-gap-dense` CSS variables.
 */
  @Input()
  set itemSpacing(v: SynFieldset['itemSpacing']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.itemSpacing = v));
  }
  get itemSpacing(): SynFieldset['itemSpacing'] {
    return this.nativeElement.itemSpacing;
  }

  /**
* Enables group-aware handling for direct child radio groups in two-column layout.
When enabled, direct child `<syn-radio-group>` elements are set to `option-layout="inline"`
unless they already define an explicit `option-layout`.
 */
  @Input()
  set groupAware(v: '' | SynFieldset['groupAware']) {
    this._ngZone.runOutsideAngular(
      () => (this.nativeElement.groupAware = v === '' || v),
    );
  }
  get groupAware(): SynFieldset['groupAware'] {
    return this.nativeElement.groupAware;
  }
}
