export const getFileHeader = (config = {}) => {
  return config.fileHeader || `// ---------------------------------------------------------------------\n// 🔒 AUTOGENERATED BY CUSTOM SHOELACE CLI\n// Removing this comment will prevent it from being managed by the CLI.\n// ---------------------------------------------------------------------\n\n`
}
