// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/angular wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';

import {
  SynAlertComponent,
  SynBadgeComponent,
  SynButtonComponent,
  SynButtonGroupComponent,
  SynCheckboxComponent,
  SynDividerComponent,
  SynDrawerComponent,
  SynDropdownComponent,
  SynHeaderComponent,
  SynIconButtonComponent,
  SynIconComponent,
  SynInputComponent,
  SynMenuComponent,
  SynMenuItemComponent,
  SynMenuLabelComponent,
  SynNavItemComponent,
  SynOptgroupComponent,
  SynOptionComponent,
  SynPopupComponent,
  SynPrioNavComponent,
  SynRadioButtonComponent,
  SynRadioComponent,
  SynRadioGroupComponent,
  SynSelectComponent,
  SynSideNavComponent,
  SynSwitchComponent,
  SynTagComponent,
  SynTextareaComponent,
} from '../components';

const components = [
  SynAlertComponent,
  SynBadgeComponent,
  SynButtonComponent,
  SynButtonGroupComponent,
  SynCheckboxComponent,
  SynDividerComponent,
  SynDrawerComponent,
  SynDropdownComponent,
  SynHeaderComponent,
  SynIconComponent,
  SynIconButtonComponent,
  SynInputComponent,
  SynMenuComponent,
  SynMenuItemComponent,
  SynMenuLabelComponent,
  SynNavItemComponent,
  SynOptgroupComponent,
  SynOptionComponent,
  SynPopupComponent,
  SynPrioNavComponent,
  SynRadioComponent,
  SynRadioButtonComponent,
  SynRadioGroupComponent,
  SynSelectComponent,
  SynSideNavComponent,
  SynSwitchComponent,
  SynTagComponent,
  SynTextareaComponent,
];

@NgModule({
  imports: components,
  exports: components,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SynergyComponentsModule {}
