// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/react wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
import * as React from 'react';
import { createComponent } from '@lit/react';
import Component from '@synergy-design-system/components/components/fieldset/fieldset.component.js';

const tagName = 'syn-fieldset';
Component.define('syn-fieldset');

/**
 * @summary Fieldsets are used to group related elements in a form.
 * @documentation https://synergy-design-system.github.io/?path=/docs/components-syn-fieldset--docs
 * @status stable
 * @since 3.18.0
 *
 * @slot - The fieldset's main content. Place form controls inside the fieldset to group them together.
 * @slot legend - Add a legend to the fieldset. This is displayed as the title of the fieldset. Alternatively, you can use the `legend` attribute.
 * @slot description - Add a description to the fieldset. This is displayed below the legend and provides additional information about the fieldset. Alternatively, you can use the `description` attribute.
 *
 * @csspart base - The component's base wrapper.
 * @csspart legend - The component's legend element.
 * @csspart description - The component's description element.
 * @csspart field-container - The container for the fieldset's fields.
 *
 * @cssproperty --item-gap - The gap between the fields in the fieldset. Defaults to `--syn-spacing-large`
 */
export const SynFieldset = createComponent({
  displayName: 'SynFieldset',
  elementClass: Component,
  events: {},
  react: React,
  tagName,
});
