/**
 * ---------------------------------------------------------------------
 * 🔒 AUTOGENERATED BY VENDORISM
 * Removing this comment will prevent it from being managed by it.
 * ---------------------------------------------------------------------
 */

/* eslint-disable */
import SynMenu from './menu.component.js';

export * from './menu.component.js';
export default SynMenu;

SynMenu.define('syn-menu');

declare global {
  interface HTMLElementTagNameMap {
    'syn-menu': SynMenu;
  }
}
