// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */

/* eslint-disable import/no-relative-packages */

import '../../../components/src/components/breadcrumb-item/breadcrumb-item';
import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import { storybookDefaults, storybookHelpers, storybookTemplate, generateStoryDescription } from '../../src/helpers/component.js';
const { args, argTypes } = storybookDefaults('syn-breadcrumb-item');
const { overrideArgs } = storybookHelpers('syn-breadcrumb-item');
const { generateTemplate } = storybookTemplate('syn-breadcrumb-item');

const meta: Meta = {
  component: 'breadcrumb-item',
  args,
  argTypes,
  title: 'Components/syn-breadcrumb-item',
  parameters: {
    docs: {
      description: {
        component: generateStoryDescription('breadcrumb-item', 'default'),
      },
    }
  }
};
export default meta;

type Story = StoryObj;

export const Default = {
  render: (args: any) => {
    return generateTemplate({ args });
  },
  parameters: {
    docs: {
      description: {
        story: generateStoryDescription('breadcrumb-item', 'default'),
      }
    }
  }
} as Story;

