// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */

/* eslint-disable import/no-relative-packages */

import '../../../components/src/components/card/card';
import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import { storybookDefaults, storybookHelpers, storybookTemplate, generateStoryDescription } from '../../src/helpers/component.js';
const { args, argTypes } = storybookDefaults('syn-card');
const { overrideArgs } = storybookHelpers('syn-card');
const { generateTemplate } = storybookTemplate('syn-card');

const meta: Meta = {
  component: 'card',
  args,
  argTypes,
  title: 'Components/syn-card',
  parameters: {
    docs: {
      description: {
        component: generateStoryDescription('card', 'default'),
      },
    }
  }
};
export default meta;

type Story = StoryObj;

export const Default = {
  render: (args: any) => {
    return generateTemplate({ args });
  },
  parameters: {
    docs: {
      description: {
        story: generateStoryDescription('card', 'default'),
      }
    }
  }
} as Story;


/**
 * Basic cards aren't very exciting, but they can display any content you want them to.
 */
export const BasicCard: Story = {
  render: () => html`<syn-card class="card-basic">
  This is just a basic card. No image, no header, and no footer. Just your content.
</syn-card>

<style>
  .card-basic {
    max-width: 300px;
  }
</style>`,
};

/**
 * Headers can be used to display titles and more.
 */
export const CardWithHeader: Story = {
  render: () => html`<syn-card class="card-header">
  <div slot="header">
    Header Title
    <syn-icon-button name="gear" label="Settings"></syn-icon-button>
  </div>

  This card has a header. You can put all sorts of things in it!
</syn-card>

<style>
  .card-header {
    max-width: 300px;
  }

  .card-header [slot='header'] {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .card-header h3 {
    margin: 0;
  }

  .card-header syn-icon-button {
    font-size: var(--syn-font-size-medium);
  }
</style>`,
};

/**
 * Footers can be used to display actions, summaries, or other relevant content.
 */
export const CardWithFooter: Story = {
  render: () => html`<syn-card class="card-footer">
  This card has a footer. You can put all sorts of things in it!

  <div slot="footer">
    <syn-rating></syn-rating>
    <syn-button variant="primary">Preview</syn-button>
  </div>
</syn-card>

<style>
  .card-footer {
    max-width: 300px;
  }

  .card-footer [slot='footer'] {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
</style>`,
};

/**
 * Cards accept an image slot. The image is displayed atop the card and stretches to fit.
 */
export const Images: Story = {
  render: () => html`<syn-card class="card-image">
  <img
    slot="image"
    src="https://images.unsplash.com/photo-1547191783-94d5f8f6d8b1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80"
    alt="A kitten walks towards camera on top of pallet."
  />
  This is a kitten, but not just any kitten. This kitten likes walking along pallets.
</syn-card>

<style>
  .card-image {
    max-width: 300px;
  }
</style>`,
};
