// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */

/* eslint-disable import/no-relative-packages */

import '../../../components/src/components/spinner/spinner';
import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import { storybookDefaults, storybookHelpers, storybookTemplate, generateStoryDescription } from '../../src/helpers/component.js';
const { args, argTypes } = storybookDefaults('syn-spinner');
const { overrideArgs } = storybookHelpers('syn-spinner');
const { generateTemplate } = storybookTemplate('syn-spinner');

const meta: Meta = {
  component: 'spinner',
  args,
  argTypes,
  title: 'Components/syn-spinner',
  parameters: {
    docs: {
      description: {
        component: generateStoryDescription('spinner', 'default'),
      },
    }
  }
};
export default meta;

type Story = StoryObj;

export const Default = {
  render: (args: any) => {
    return generateTemplate({ args });
  },
  parameters: {
    docs: {
      description: {
        story: generateStoryDescription('spinner', 'default'),
      }
    }
  }
} as Story;


/**
 * Spinners are sized based on the current font size. To change their size, set the font-size property on the spinner itself or on a parent element as shown below.
 */
export const Size: Story = {
  render: () => html`<syn-spinner></syn-spinner>
<syn-spinner style="font-size: 2rem;"></syn-spinner>
<syn-spinner style="font-size: 3rem;"></syn-spinner>`,
};

/**
 * The width of the spinner's track can be changed by setting the --track-width custom property.
 */
export const TrackWidth: Story = {
  render: () => html`<syn-spinner style="font-size: 50px; --track-width: 10px;"></syn-spinner>`,
};

/**
 * The spinner's colors can be changed by setting the --indicator-color and --track-color custom properties.
 */
export const Color: Story = {
  render: () => html`<syn-spinner style="font-size: 3rem; --indicator-color: deeppink; --track-color: pink;"></syn-spinner>`,
};
