// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/react wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
import * as React from 'react';
import { createComponent } from '@lit/react';
import Component from '@synergy-design-system/components/components/checkbox-group/checkbox-group.component.js';

const tagName = 'syn-checkbox-group';
Component.define('syn-checkbox-group');

/**
 * @summary Checkbox groups are used to group multiple checkboxes together.
 * @documentation https://synergy-design-system.github.io/?path=/docs/components-syn-checkbox-group--docs
 * @status stable
 * @since 3.18.x
 *
 * @slot - The default slot where `<syn-checkbox>` and `<syn-switch>` elements are placed.
 * @slot label - The checkbox group's label. Required for proper accessibility. Alternatively, you can use the `label`
 *  attribute.
 * @slot help-text - Text that describes how to use the checkbox group. Alternatively, you can use the `help-text` attribute.
 *
 * @csspart form-control - The form control that wraps the label, input, and help text.
 * @csspart form-control-label - The label's wrapper.
 * @csspart form-control-input - The input's wrapper.
 * @csspart form-control-help-text - The help text's wrapper.
 */
export const SynCheckboxGroup = createComponent({
  displayName: 'SynCheckboxGroup',
  elementClass: Component,
  events: {},
  react: React,
  tagName,
});
