// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */
import SynBreadcrumb from './breadcrumb.component.js';

export * from './breadcrumb.component.js';
export default SynBreadcrumb;

SynBreadcrumb.define('syn-breadcrumb');

declare global {
  interface HTMLElementTagNameMap {
    'syn-breadcrumb': SynBreadcrumb;
  }
}
