// !!! This file is automatically generated via scripts/build.js
// !!! Changes you apply to this file will get lost
// !!! Please add your wanted events to the `events` array in scripts/vendorism.js
// !!! or add a new typescript file to the src/events folder
// !!! and run `pnpm build` to recreate this index file
export type * from './syn-blur.ts';
export type * from './syn-change.ts';
export type * from './syn-clear.ts';
export type * from './syn-error.ts';
export type * from './syn-focus.ts';
export type * from './syn-input.ts';
export type * from './syn-invalid.ts';
export type * from './syn-load.ts';
export type * from './syn-remove.ts';
