// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/angular wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
import {
  Component,
  ElementRef,
  NgZone,
  Input,
  Output,
  EventEmitter,
  AfterContentInit,
} from '@angular/core';
import type { SynPagination } from '@synergy-design-system/components';

import '@synergy-design-system/components/components/pagination/pagination.js';

/**
 * @summary The default pagination offers the most comprehensive controls and is optimized for tables, lists, and complex data views.
 * It is intended for use cases where users need to adjust both the number of displayed rows and the active page.
 * The navigation controls allow switching between pages as well as jumping directly to the first or last page.
 *
 * @documentation https://synergy-design-system.github.io/?path=/docs/components-syn-pagination--docs
 * @status stable
 * @since 3.0.0
 *
 * @csspart base - The component's base wrapper.
 */
@Component({
  selector: 'syn-pagination',
  standalone: true,
  template: '<ng-content></ng-content>',
})
export class SynPaginationComponent {
  public nativeElement: SynPagination;
  private _ngZone: NgZone;

  constructor(e: ElementRef, ngZone: NgZone) {
    this.nativeElement = e.nativeElement;
    this._ngZone = ngZone;
  }

  /**
   * When true, a divider is displayed between the page navigation controls and the rows-per-page selector.
   */
  @Input()
  set divider(v: '' | SynPagination['divider']) {
    this._ngZone.runOutsideAngular(
      () => (this.nativeElement.divider = v === '' || v),
    );
  }
  get divider(): SynPagination['divider'] {
    return this.nativeElement.divider;
  }

  /**
   * When true, the pagination controls are disabled and non-interactive.
   */
  @Input()
  set disabled(v: '' | SynPagination['disabled']) {
    this._ngZone.runOutsideAngular(
      () => (this.nativeElement.disabled = v === '' || v),
    );
  }
  get disabled(): SynPagination['disabled'] {
    return this.nativeElement.disabled;
  }

  /**
   * The size of the pagination controls.
   */
  @Input()
  set size(v: SynPagination['size']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.size = v));
  }
  get size(): SynPagination['size'] {
    return this.nativeElement.size;
  }

  /**
* The current page number.
* The default value is 1.
The component will emit a "page-change" event whenever the page changes, allowing you to respond to page changes in your application.
 */
  @Input()
  set currentPage(v: SynPagination['currentPage']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.currentPage = v));
  }
  get currentPage(): SynPagination['currentPage'] {
    return this.nativeElement.currentPage;
  }

  /**
* The number of items to display per page.
* The default value is 25.
The component will emit a "page-size-change" event whenever the page size changes, allowing you to respond to page size changes in your application.
 */
  @Input()
  set pageSize(v: SynPagination['pageSize']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.pageSize = v));
  }
  get pageSize(): SynPagination['pageSize'] {
    return this.nativeElement.pageSize;
  }

  /**
* An array of numbers representing the available options for the number of items to display per page.
* The default value is [10, 25, 50, 100].
The component will use this array to populate the rows-per-page selector, allowing users to choose from the specified options.
 */
  @Input()
  set pageSizeOptions(v: SynPagination['pageSizeOptions']) {
    this._ngZone.runOutsideAngular(
      () => (this.nativeElement.pageSizeOptions = v),
    );
  }
  get pageSizeOptions(): SynPagination['pageSizeOptions'] {
    return this.nativeElement.pageSizeOptions;
  }

  /**
   * Total amount of items.
   * The component will use this value to calculate the total number of pages based on the selected rows per page.
   */
  @Input()
  set totalItems(v: SynPagination['totalItems']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.totalItems = v));
  }
  get totalItems(): SynPagination['totalItems'] {
    return this.nativeElement.totalItems;
  }

  /**
* The pagination variant to use.
* The "full" variant includes comprehensive controls for navigating between pages and adjusting the number of displayed rows,
while the "compact" variant offers a streamlined interface with essential navigation controls.
The default value is "full".
 */
  @Input()
  set variant(v: SynPagination['variant']) {
    this._ngZone.runOutsideAngular(() => (this.nativeElement.variant = v));
  }
  get variant(): SynPagination['variant'] {
    return this.nativeElement.variant;
  }
}
