import type { Preview } from "@storybook/web-components";

import { setCustomElementsManifest } from '@storybook/web-components';
import '../../../vendor/docs/assets/styles/docs.css';
import '../../../vendor/src/themes/_utility.css';
import '../../tokens/src/light.css';
import '../src/components';


/**
 * This loads the custom elements manifest generated on run or on build time.
 */

async function loadCustomElements() {
  fetch('./custom-elements.json')
    .then(async () => {
      // Use dynamic manifest generated by Vite on runtime
      return await fetch('./custom-elements.json').then(res => { console.log(res); return res.json(); });
    })
    .then(async customElements => {
      setCustomElementsManifest(customElements);
    });

  console.log('Custom elements manifest loaded');
}

loadCustomElements();

const preview: Preview = {
  parameters: {
    docs: {
      stories: { inline: false }
    },
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;

