<script setup lang="ts">
// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/vue wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------

/**
 * @summary The default pagination offers the most comprehensive controls and is optimized for tables, lists, and complex data views.
 * It is intended for use cases where users need to adjust both the number of displayed rows and the active page.
 * The navigation controls allow switching between pages as well as jumping directly to the first or last page.
 *
 * @documentation https://synergy-design-system.github.io/?path=/docs/components-syn-pagination--docs
 * @status stable
 * @since 3.0.0
 *
 * @csspart base - The component's base wrapper.
 */
import { computed, ref } from 'vue';
import '@synergy-design-system/components/components/pagination/pagination.js';

import type { SynPagination } from '@synergy-design-system/components';

// DOM Reference to the element
const nativeElement = ref<SynPagination>();

defineExpose({
  nativeElement,
});

// Map attributes
const props = defineProps<{
  /**
   * When true, a divider is displayed between the page navigation controls and the rows-per-page selector.
   */
  divider?: SynPagination['divider'];

  /**
   * When true, the pagination controls are disabled and non-interactive.
   */
  disabled?: SynPagination['disabled'];

  /**
   * The size of the pagination controls.
   */
  size?: SynPagination['size'];

  /**
* The current page number.
* The default value is 1.
The component will emit a "page-change" event whenever the page changes, allowing you to respond to page changes in your application.
 */
  currentPage?: SynPagination['currentPage'];

  /**
* The number of items to display per page.
* The default value is 25.
The component will emit a "page-size-change" event whenever the page size changes, allowing you to respond to page size changes in your application.
 */
  pageSize?: SynPagination['pageSize'];

  /**
* An array of numbers representing the available options for the number of items to display per page.
* The default value is [10, 25, 50, 100].
The component will use this array to populate the rows-per-page selector, allowing users to choose from the specified options.
 */
  pageSizeOptions?: SynPagination['pageSizeOptions'];

  /**
   * Total amount of items.
   * The component will use this value to calculate the total number of pages based on the selected rows per page.
   */
  totalItems?: SynPagination['totalItems'];

  /**
* The pagination variant to use.
* The "full" variant includes comprehensive controls for navigating between pages and adjusting the number of displayed rows,
while the "compact" variant offers a streamlined interface with essential navigation controls.
The default value is "full".
 */
  variant?: SynPagination['variant'];
}>();

// Make sure prop binding only forwards the props that are actually there.
// This is needed because :param="param" also adds an empty attribute
// when using web-components, which breaks optional arguments like size in SynInput
// @see https://github.com/vuejs/core/issues/5190#issuecomment-1003112498
const visibleProps = computed(() =>
  Object.fromEntries(
    Object.entries(props).filter(([, value]) => typeof value !== 'undefined'),
  ),
);
</script>

<template>
  <syn-pagination v-bind="visibleProps" ref="nativeElement"> </syn-pagination>
</template>
