<script setup lang="ts">
// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/vue wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------

/**
 * @summary Switches allow the user to toggle an option on or off.
 * @documentation https://synergy.style/components/switch
 * @status stable
 * @since 2.0
 *
 * @slot - The switch's label.
 *
 * @event syn-blur - Emitted when the control loses focus.
 * @event syn-change - Emitted when the control's checked state changes.
 * @event syn-input - Emitted when the control receives input.
 * @event syn-focus - Emitted when the control gains focus.
 * @event syn-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 *
 * @csspart base - The component's base wrapper.
 * @csspart control - The control that houses the switch's thumb.
 * @csspart thumb - The switch's thumb.
 * @csspart label - The switch's label.
 *
 * @cssproperty --width - The width of the switch.
 * @cssproperty --height - The height of the switch.
 * @cssproperty --thumb-size - The size of the thumb.
 */
import { computed, ref } from 'vue';
import '@synergy-design-system/components/components/switch/switch.js';

import type {
  SynBlurEvent, SynChangeEvent, SynFocusEvent, SynInputEvent, SynInvalidEvent, SynSwitch,
} from '@synergy-design-system/components';

// DOM Reference to the element
const element = ref<SynSwitch>();

// Map methods
const callHandleCheckedChange = (...args: Parameters<SynSwitch['handleCheckedChange']>) => element.value?.handleCheckedChange(...args);
const callHandleDisabledChange = (...args: Parameters<SynSwitch['handleDisabledChange']>) => element.value?.handleDisabledChange(...args);
/**
* Simulates a click on the switch.
 */
const callClick = (...args: Parameters<SynSwitch['click']>) => element.value?.click(...args);
/**
* Sets focus on the switch.
 */
const callFocus = (...args: Parameters<SynSwitch['focus']>) => element.value?.focus(...args);
/**
* Removes focus from the switch.
 */
const callBlur = (...args: Parameters<SynSwitch['blur']>) => element.value?.blur(...args);
/**
* Checks for validity but does not show a validation message.
* Returns `true` when valid and `false` when invalid.
 */
const callCheckValidity = (...args: Parameters<SynSwitch['checkValidity']>) => element.value?.checkValidity(...args);
/**
* Gets the associated form, if one exists.
 */
const callGetForm = (...args: Parameters<SynSwitch['getForm']>) => element.value?.getForm(...args);
/**
* Checks for validity and shows the browser's validation message if the control is invalid.
 */
const callReportValidity = (...args: Parameters<SynSwitch['reportValidity']>) => element.value?.reportValidity(...args);
/**
* Sets a custom validation message.
* Pass an empty string to restore validity.
 */
const callSetCustomValidity = (...args: Parameters<SynSwitch['setCustomValidity']>) => element.value?.setCustomValidity(...args);

defineExpose({
  callHandleCheckedChange,
  callHandleDisabledChange,
  callClick,
  callFocus,
  callBlur,
  callCheckValidity,
  callGetForm,
  callReportValidity,
  callSetCustomValidity,
});

// Map attributes
const props = defineProps<{
  'title'?: SynSwitch['title'];

  /**
* The name of the switch, submitted as a name/value pair with form data.
 */
  'name'?: SynSwitch['name'];

  /**
* The current value of the switch, submitted as a name/value pair with form data.
 */
  'value'?: SynSwitch['value'];

  /**
* The switch's size.
 */
  'size'?: SynSwitch['size'];

  /**
* Disables the switch.
 */
  'disabled'?: SynSwitch['disabled'];

  /**
* Draws the switch in a checked state.
 */
  'checked'?: SynSwitch['checked'];

  /**
* By default, form controls are associated with the nearest containing `<form>` element.
* This attribute allows you
to place the form control outside of a form and associate it with the form that has this `id`.
* The form must be in
the same document or shadow root for this to work.
 */
  'form'?: SynSwitch['form'];

  /**
* Makes the switch a required field.
 */
  'required'?: SynSwitch['required'];
}>();

// Make sure prop binding only forwards the props that are actually there.
// This is needed because :param="param" also adds an empty attribute
// when using web-components, which breaks optional arguments like size in SynInput
// @see https://github.com/vuejs/core/issues/5190#issuecomment-1003112498
const visibleProps = computed(() => Object.fromEntries(
  Object
    .entries(props)
    .filter(([, value]) => typeof value !== 'undefined'),
));

// Map events
defineEmits<{
  /**
* Emitted when the control loses focus.
 */
  'syn-blur': [e: SynBlurEvent];

  /**
* Emitted when the control's checked state changes.
 */
  'syn-change': [e: SynChangeEvent];

  /**
* Emitted when the control receives input.
 */
  'syn-input': [e: SynInputEvent];

  /**
* Emitted when the control gains focus.
 */
  'syn-focus': [e: SynFocusEvent];

  /**
* Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 */
  'syn-invalid': [e: SynInvalidEvent];
}>();
</script>

<template>
  <syn-switch
    v-bind="visibleProps"
    ref="element"
    @syn-blur="$emit('syn-blur', $event)"
    @syn-change="$emit('syn-change', $event)"
    @syn-input="$emit('syn-input', $event)"
    @syn-focus="$emit('syn-focus', $event)"
    @syn-invalid="$emit('syn-invalid', $event)"
  >
    <slot />
  </syn-switch>
</template>
