<script setup lang="ts">
// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/vue wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------

/**
 * @summary Textareas collect data from the user and allow multiple lines of text.
 * @documentation https://synergy.style/components/textarea
 * @status stable
 * @since 2.0
 *
 * @slot label - The textarea's label. Alternatively, you can use the `label` attribute.
 * @slot help-text - Text that describes how to use the input. Alternatively, you can use the `help-text` attribute.
 *
 * @event syn-blur - Emitted when the control loses focus.
 * @event syn-change - Emitted when an alteration to the control's value is committed by the user.
 * @event syn-focus - Emitted when the control gains focus.
 * @event syn-input - Emitted when the control receives input.
 * @event syn-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 *
 * @csspart form-control - The form control that wraps the label, input, and help text.
 * @csspart form-control-label - The label's wrapper.
 * @csspart form-control-input - The input's wrapper.
 * @csspart form-control-help-text - The help text's wrapper.
 * @csspart base - The component's base wrapper.
 * @csspart textarea - The internal `<textarea>` control.
 */
import { computed, ref } from 'vue';
import '@synergy-design-system/components/components/textarea/textarea.js';

import type {
  SynBlurEvent, SynChangeEvent, SynFocusEvent, SynInputEvent, SynInvalidEvent, SynTextarea,
} from '@synergy-design-system/components';

// DOM Reference to the element
const element = ref<SynTextarea>();

// Map methods
const callHandleDisabledChange = (...args: Parameters<SynTextarea['handleDisabledChange']>) => element.value?.handleDisabledChange(...args);
const callHandleRowsChange = (...args: Parameters<SynTextarea['handleRowsChange']>) => element.value?.handleRowsChange(...args);
const callHandleValueChange = (...args: Parameters<SynTextarea['handleValueChange']>) => element.value?.handleValueChange(...args);
/**
* Sets focus on the textarea.
 */
const callFocus = (...args: Parameters<SynTextarea['focus']>) => element.value?.focus(...args);
/**
* Removes focus from the textarea.
 */
const callBlur = (...args: Parameters<SynTextarea['blur']>) => element.value?.blur(...args);
/**
* Selects all the text in the textarea.
 */
const callSelect = (...args: Parameters<SynTextarea['select']>) => element.value?.select(...args);
/**
* Gets or sets the textarea's scroll position.
 */
const callScrollPosition = (...args: Parameters<SynTextarea['scrollPosition']>) => element.value?.scrollPosition(...args);
/**
* Sets the start and end positions of the text selection (0-based).
 */
const callSetSelectionRange = (...args: Parameters<SynTextarea['setSelectionRange']>) => element.value?.setSelectionRange(...args);
/**
* Replaces a range of text with a new string.
 */
const callSetRangeText = (...args: Parameters<SynTextarea['setRangeText']>) => element.value?.setRangeText(...args);
/**
* Checks for validity but does not show a validation message.
* Returns `true` when valid and `false` when invalid.
 */
const callCheckValidity = (...args: Parameters<SynTextarea['checkValidity']>) => element.value?.checkValidity(...args);
/**
* Gets the associated form, if one exists.
 */
const callGetForm = (...args: Parameters<SynTextarea['getForm']>) => element.value?.getForm(...args);
/**
* Checks for validity and shows the browser's validation message if the control is invalid.
 */
const callReportValidity = (...args: Parameters<SynTextarea['reportValidity']>) => element.value?.reportValidity(...args);
/**
* Sets a custom validation message.
* Pass an empty string to restore validity.
 */
const callSetCustomValidity = (...args: Parameters<SynTextarea['setCustomValidity']>) => element.value?.setCustomValidity(...args);

defineExpose({
  callHandleDisabledChange,
  callHandleRowsChange,
  callHandleValueChange,
  callFocus,
  callBlur,
  callSelect,
  callScrollPosition,
  callSetSelectionRange,
  callSetRangeText,
  callCheckValidity,
  callGetForm,
  callReportValidity,
  callSetCustomValidity,
});

// Map attributes
const props = defineProps<{
  'title'?: SynTextarea['title'];

  /**
* The name of the textarea, submitted as a name/value pair with form data.
 */
  'name'?: SynTextarea['name'];

  /**
* The current value of the textarea, submitted as a name/value pair with form data.
 */
  'value'?: SynTextarea['value'];

  /**
* The textarea's size.
 */
  'size'?: SynTextarea['size'];

  /**
* The textarea's label.
* If you need to display HTML, use the `label` slot instead.
 */
  'label'?: SynTextarea['label'];

  /**
* The textarea's help text.
* If you need to display HTML, use the `help-text` slot instead.
 */
  'helpText'?: SynTextarea['helpText'];

  /**
* Placeholder text to show as a hint when the input is empty.
 */
  'placeholder'?: SynTextarea['placeholder'];

  /**
* The number of rows to display by default.
 */
  'rows'?: SynTextarea['rows'];

  /**
* Controls how the textarea can be resized.
 */
  'resize'?: SynTextarea['resize'];

  /**
* Disables the textarea.
 */
  'disabled'?: SynTextarea['disabled'];

  /**
* Makes the textarea readonly.
 */
  'readonly'?: SynTextarea['readonly'];

  /**
* By default, form controls are associated with the nearest containing `<form>` element.
* This attribute allows you
to place the form control outside of a form and associate it with the form that has this `id`.
* The form must be in
the same document or shadow root for this to work.
 */
  'form'?: SynTextarea['form'];

  /**
* Makes the textarea a required field.
 */
  'required'?: SynTextarea['required'];

  /**
* The minimum length of input that will be considered valid.
 */
  'minlength'?: SynTextarea['minlength'];

  /**
* The maximum length of input that will be considered valid.
 */
  'maxlength'?: SynTextarea['maxlength'];

  /**
* Controls whether and how text input is automatically capitalized as it is entered by the user.
 */
  'autocapitalize'?: SynTextarea['autocapitalize'];

  /**
* Indicates whether the browser's autocorrect feature is on or off.
 */
  'autocorrect'?: SynTextarea['autocorrect'];

  /**
* Specifies what permission the browser has to provide assistance in filling out form field values.
* Refer to
[this page on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) for available values.
 */
  'autocomplete'?: SynTextarea['autocomplete'];

  /**
* Indicates that the input should receive focus on page load.
 */
  'autofocus'?: SynTextarea['autofocus'];

  /**
* Used to customize the label or icon of the Enter key on virtual keyboards.
 */
  'enterkeyhint'?: SynTextarea['enterkeyhint'];

  /**
* Enables spell checking on the textarea.
 */
  'spellcheck'?: SynTextarea['spellcheck'];

  /**
* Tells the browser what type of data will be entered by the user, allowing it to display the appropriate virtual
keyboard on supportive devices.
 */
  'inputmode'?: SynTextarea['inputmode'];

  /**
* Support for two way data binding
 */
  modelValue?: SynTextarea['value'];
}>();

// Make sure prop binding only forwards the props that are actually there.
// This is needed because :param="param" also adds an empty attribute
// when using web-components, which breaks optional arguments like size in SynInput
// @see https://github.com/vuejs/core/issues/5190#issuecomment-1003112498
const visibleProps = computed(() => Object.fromEntries(
  Object
    .entries(props)
    .filter(([, value]) => typeof value !== 'undefined'),
));

// Map events
defineEmits<{
  /**
* Emitted when the control loses focus.
 */
  'syn-blur': [e: SynBlurEvent];

  /**
* Emitted when an alteration to the control's value is committed by the user.
 */
  'syn-change': [e: SynChangeEvent];

  /**
* Emitted when the control gains focus.
 */
  'syn-focus': [e: SynFocusEvent];

  /**
* Emitted when the control receives input.
 */
  'syn-input': [e: SynInputEvent];

  /**
* Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 */
  'syn-invalid': [e: SynInvalidEvent];

  /**
* Support for two way data binding
 */
  'update:modelValue': [newValue: SynTextarea['value']];
}>();
</script>

<template>
  <syn-textarea
    v-bind="visibleProps"
    ref="element"
    @syn-blur="$emit('syn-blur', $event)"
    @syn-change="$emit('syn-change', $event)"
    @syn-focus="$emit('syn-focus', $event)"
    @syn-input="$emit('update:modelValue', $event.target.value); $emit('syn-input', $event)"
    @syn-invalid="$emit('syn-invalid', $event)"
  >
    <slot name="label" />
    <slot name="help-text" />
  </syn-textarea>
</template>
