<script setup lang="ts">
// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/vue wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------

/**
 * @summary Flexible button / link component that can be used to quickly build navigations.
 * Takes one of 3 forms:
 * - link (overrides all other if 'href' is provided),
 * - button (default),
 * - or accordion (if 'children' slot defined).
 *
 * @status stable
 * @since 1.11.0
 *
 * @dependency syn-divider
 *
 * @event syn-show - Emitted when the navigation item:
 * - has children,
 * - has no href
 * - and is clicked while HTML details are hidden.
 *
 * @event syn-hide - Emitted when the navigation item:
 * - has children,
 * - has no href
 * - and is clicked while HTML details are shown.
 *
 * @slot - The navigation item's label.
 * @slot prefix - A presentational prefix icon or similar element.
 * @slot suffix - A presentational suffix icon or similar element.
 * @slot children - Slot used to provide nested child navigation elements.
 * If provided, details and summary elements will be used.
 * A chevron will be shown on the right side regardless of the chevron property.
 *
 * @csspart base - The component's base wrapper including children.
 * @csspart children - The wrapper that holds the children
 * @csspart content-wrapper - The component's content wrapper.
 * @csspart content - The component's content excluding children.
 * @csspart current-indicator - The indicator used when current is set to true
 * @csspart chevron - The container that wraps the chevron.
 * @csspart details - The details element rendered when there are children available
 * @csspart divider - The components optional top divider.
 * @csspart prefix - The container that wraps the prefix.
 * @csspart suffix - The container that wraps the suffix.
 *
 * @cssproperty --level - Numeric value, indicating the level the item is placed at.
 * @cssproperty --level-stepping - The amount of pixels each level will indent.
 */
import { computed, ref } from 'vue';
import '@synergy-design-system/components/components/nav-item/nav-item.js';

import type { SynHideEvent, SynNavItem, SynShowEvent } from '@synergy-design-system/components';

// DOM Reference to the element
const element = ref<SynNavItem>();

// Map methods

defineExpose({

});

// Map attributes
const props = defineProps<{
  /**
* The navigation item's href target.
If provided, the navigation item will use an anchor tag otherwise it will use a button tag.
The 'children' slot and accordion behavior will be ignored if an 'href' is provided.
 */
  'href'?: SynNavItem['href'];

  'current'?: SynNavItem['current'];

  /**
* Disables the navigation item.
 */
  'disabled'?: SynNavItem['disabled'];

  /**
* The navigation item's orientation.
 */
  'vertical'?: SynNavItem['vertical'];

  /**
* Appends a chevron to the right side of a navigation item.
Only used if `vertical` is true.
 */
  'chevron'?: SynNavItem['chevron'];

  /**
* Reflects HTML details element state and allows control from parent.
Only used if `vertical` is true, no `href`is undefined, and `children` is defined.
 */
  'open'?: SynNavItem['open'];

  /**
* Toggle to true to show a divider above the element.
Only available when vertical
 */
  'divider'?: SynNavItem['divider'];
}>();

// Make sure prop binding only forwards the props that are actually there.
// This is needed because :param="param" also adds an empty attribute
// when using web-components, which breaks optional arguments like size in SynInput
// @see https://github.com/vuejs/core/issues/5190#issuecomment-1003112498
const visibleProps = computed(() => Object.fromEntries(
  Object
    .entries(props)
    .filter(([, value]) => typeof value !== 'undefined'),
));

// Map events
defineEmits<{
  /**
* Emitted when the navigation item: - has children, - has no href - and is clicked while HTML details are hidden.
 */
  'syn-show': [e: SynShowEvent];

  /**
* Emitted when the navigation item: - has children, - has no href - and is clicked while HTML details are shown.
 */
  'syn-hide': [e: SynHideEvent];
}>();
</script>

<script lang="ts">
export type { SynShowEvent } from '@synergy-design-system/components';
export type { SynHideEvent } from '@synergy-design-system/components';
</script>

<template>
  <syn-nav-item
    v-bind="visibleProps"
    ref="element"

    @syn-show="$emit('syn-show', $event)"
    @syn-hide="$emit('syn-hide', $event)"
  >
    <slot />
    <slot name="prefix" />
    <slot name="suffix" />
    <slot name="children" />
  </syn-nav-item>
</template>
