<script setup lang="ts">
// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/vue wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------

/**
 * @summary Validate is a helper that may be used to wrap
 * synergy input fields and forms to provide validation message.
 *
 * @dependency syn-alert
 *
 * @slot - The input fields or form element to be validated.
 * Avoid slotting in more than one element, as subsequent ones will be ignored.
 *
 * @csspart base - The component's base wrapper.
 * @csspart input-wrapper - The container that wraps the input field.
 * @csspart alert - The container that wraps the alert.
 * @csspart alert-message - The container that wraps the alert message.
 */
import { computed, ref } from 'vue';
import '@synergy-design-system/components/components/validate/validate.js';

import type { SynValidate } from '@synergy-design-system/components';

// DOM Reference to the element
const nativeElement = ref<SynValidate>();

defineExpose({
  nativeElement,
});

// Map attributes
const props = defineProps<{
  /**
* Show the invalid message underneath the element, using a syn-alert
 */
  'inline'?: SynValidate['inline'];

  /**
* Do not show the error icon when using inline validation
 */
  'hideIcon'?: SynValidate['hideIcon'];

  /**
* Enable to validate on each input change (e.g.
* when a keystroke occurs on an input)
instead of form submit.
 */
  'live'?: SynValidate['live'];

  /**
* Custom validation message to be displayed when the input is invalid.
Will override the default browser validation message.
 */
  'customValidation'?: SynValidate['customValidation'];
}>();

// Make sure prop binding only forwards the props that are actually there.
// This is needed because :param="param" also adds an empty attribute
// when using web-components, which breaks optional arguments like size in SynInput
// @see https://github.com/vuejs/core/issues/5190#issuecomment-1003112498
const visibleProps = computed(() => Object.fromEntries(
  Object
    .entries(props)
    .filter(([, value]) => typeof value !== 'undefined'),
));

</script>

<template>
  <syn-validate

    v-bind="visibleProps"
    ref="nativeElement"
  >
    <slot />
  </syn-validate>
</template>
