// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED @synergy-design-system/angular wrappers for @synergy-design-system/components
// Please do not edit this file directly!
// It will get recreated when running pnpm build.
// ---------------------------------------------------------------------
export { SynAlertComponent } from './alert.component';
export { SynBadgeComponent } from './badge.component';
export { SynButtonComponent } from './button.component';
export { SynButtonGroupComponent } from './button-group.component';
export { SynCheckboxComponent } from './checkbox.component';
export { SynDialogComponent } from './dialog.component';
export { SynDividerComponent } from './divider.component';
export { SynDrawerComponent } from './drawer.component';
export { SynDropdownComponent } from './dropdown.component';
export { SynHeaderComponent } from './header.component';
export { SynIconButtonComponent } from './icon-button.component';
export { SynIconComponent } from './icon.component';
export { SynInputComponent } from './input.component';
export { SynMenuComponent } from './menu.component';
export { SynMenuItemComponent } from './menu-item.component';
export { SynMenuLabelComponent } from './menu-label.component';
export { SynNavItemComponent } from './nav-item.component';
export { SynOptgroupComponent } from './optgroup.component';
export { SynOptionComponent } from './option.component';
export { SynPopupComponent } from './popup.component';
export { SynPrioNavComponent } from './prio-nav.component';
export { SynProgressBarComponent } from './progress-bar.component';
export { SynProgressRingComponent } from './progress-ring.component';
export { SynRadioButtonComponent } from './radio-button.component';
export { SynRadioComponent } from './radio.component';
export { SynRadioGroupComponent } from './radio-group.component';
export { SynSelectComponent } from './select.component';
export { SynSideNavComponent } from './side-nav.component';
export { SynSpinnerComponent } from './spinner.component';
export { SynSwitchComponent } from './switch.component';
export { SynTagComponent } from './tag.component';
export { SynTextareaComponent } from './textarea.component';
export { SynTooltipComponent } from './tooltip.component';
