/**
 * ---------------------------------------------------------------------
 * 🔒 AUTOGENERATED BY VENDORISM
 * Removing this comment will prevent it from being managed by it.
 * ---------------------------------------------------------------------
 */

/* eslint-disable */
import '../../../dist/synergy.js';
import { aTimeout, expect, fixture, html, oneEvent, waitUntil } from '@open-wc/testing';
import { clickOnElement } from '../../internal/test.js';
import { runFormControlBaseTests } from '../../internal/test/form-control-base-tests.js';
import { sendKeys } from '@web/test-runner-commands';
import sinon from 'sinon';
import type { SynChangeEvent } from '../../events/syn-change.js';
import type SynRadio from '../radio/radio.js';
import type SynRadioGroup from './radio-group.js';

describe('<syn-radio-group>', () => {
  describe('validation tests', () => {
    it('should be invalid initially when required and no radio is checked', async () => {
      const radioGroup = await fixture<SynRadioGroup>(html`
        <syn-radio-group required>
          <syn-radio value="1"></syn-radio>
          <syn-radio value="2"></syn-radio>
        </syn-radio-group>
      `);

      expect(radioGroup.checkValidity()).to.be.false;
    });

    it('should become valid when an option is checked', async () => {
      const radioGroup = await fixture<SynRadioGroup>(html`
        <syn-radio-group required>
          <syn-radio value="1"></syn-radio>
          <syn-radio value="2"></syn-radio>
        </syn-radio-group>
      `);

      radioGroup.value = '1';
      await radioGroup.updateComplete;

      expect(radioGroup.checkValidity()).to.be.true;
    });

    it(`should be valid when required and one radio is checked`, async () => {
      const el = await fixture<SynRadioGroup>(html`
        <syn-radio-group label="Select an option" value="1" required>
          <syn-radio name="option" value="1">Option 1</syn-radio>
          <syn-radio name="option" value="2">Option 2</syn-radio>
          <syn-radio name="option" value="3">Option 3</syn-radio>
        </syn-radio-group>
      `);

      expect(el.checkValidity()).to.be.true;
    });

    it(`should be invalid when required and no radios are checked`, async () => {
      const el = await fixture<SynRadioGroup>(html`
        <syn-radio-group label="Select an option" required>
          <syn-radio name="option" value="1">Option 1</syn-radio>
          <syn-radio name="option" value="2">Option 2</syn-radio>
          <syn-radio name="option" value="3">Option 3</syn-radio>
        </syn-radio-group>
      `);

      expect(el.checkValidity()).to.be.false;
    });

    it(`should be valid when required and a different radio is checked`, async () => {
      const el = await fixture<SynRadioGroup>(html`
        <syn-radio-group label="Select an option" value="3" required>
          <syn-radio name="option" value="1">Option 1</syn-radio>
          <syn-radio name="option" value="2">Option 2</syn-radio>
          <syn-radio name="option" value="3">Option 3</syn-radio>
        </syn-radio-group>
      `);

      expect(el.checkValidity()).to.be.true;
    });

    it(`should be invalid when custom validity is set`, async () => {
      const el = await fixture<SynRadioGroup>(html`
        <syn-radio-group label="Select an option">
          <syn-radio name="option" value="1">Option 1</syn-radio>
          <syn-radio name="option" value="2">Option 2</syn-radio>
          <syn-radio name="option" value="3">Option 3</syn-radio>
        </syn-radio-group>
      `);

      el.setCustomValidity('Error');

      expect(el.checkValidity()).to.be.false;
    });

    it('should receive the correct validation attributes ("states") when valid', async () => {
      const radioGroup = await fixture<SynRadioGroup>(html`
        <syn-radio-group value="1" required>
          <syn-radio value="1"></syn-radio>
          <syn-radio value="2"></syn-radio>
        </syn-radio-group>
      `);
      const secondRadio = radioGroup.querySelectorAll('syn-radio')[1];

      expect(radioGroup.checkValidity()).to.be.true;
      expect(radioGroup.hasAttribute('data-required')).to.be.true;
      expect(radioGroup.hasAttribute('data-optional')).to.be.false;
      expect(radioGroup.hasAttribute('data-invalid')).to.be.false;
      expect(radioGroup.hasAttribute('data-valid')).to.be.true;
      expect(radioGroup.hasAttribute('data-user-invalid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-valid')).to.be.false;

      await clickOnElement(secondRadio);
      await secondRadio.updateComplete;

      expect(radioGroup.checkValidity()).to.be.true;
      expect(radioGroup.hasAttribute('data-user-invalid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-valid')).to.be.true;
    });

    it('should receive the correct validation attributes ("states") when invalid', async () => {
      const radioGroup = await fixture<SynRadioGroup>(html`
        <syn-radio-group required>
          <syn-radio value="1"></syn-radio>
          <syn-radio value="2"></syn-radio>
        </syn-radio-group>
      `);
      const secondRadio = radioGroup.querySelectorAll('syn-radio')[1];

      expect(radioGroup.hasAttribute('data-required')).to.be.true;
      expect(radioGroup.hasAttribute('data-optional')).to.be.false;
      expect(radioGroup.hasAttribute('data-invalid')).to.be.true;
      expect(radioGroup.hasAttribute('data-valid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-invalid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-valid')).to.be.false;

      await clickOnElement(secondRadio);
      radioGroup.value = '';
      await radioGroup.updateComplete;

      expect(radioGroup.hasAttribute('data-user-invalid')).to.be.true;
      expect(radioGroup.hasAttribute('data-user-valid')).to.be.false;
    });

    it('should receive validation attributes ("states") even when novalidate is used on the parent form', async () => {
      const el = await fixture<HTMLFormElement>(html`
        <form novalidate>
          <syn-radio-group required>
            <syn-radio value="1"></syn-radio>
            <syn-radio value="2"></syn-radio>
          </syn-radio-group>
        </form>
      `);
      const radioGroup = el.querySelector<SynRadioGroup>('syn-radio-group')!;

      expect(radioGroup.hasAttribute('data-required')).to.be.true;
      expect(radioGroup.hasAttribute('data-optional')).to.be.false;
      expect(radioGroup.hasAttribute('data-invalid')).to.be.true;
      expect(radioGroup.hasAttribute('data-valid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-invalid')).to.be.false;
      expect(radioGroup.hasAttribute('data-user-valid')).to.be.false;
    });

    it('should show a constraint validation error when setCustomValidity() is called', async () => {
      const form = await fixture<HTMLFormElement>(html`
        <form>
          <syn-radio-group value="1">
            <syn-radio id="radio-1" name="a" value="1"></syn-radio>
            <syn-radio id="radio-2" name="a" value="2"></syn-radio>
          </syn-radio-group>
          <syn-button type="submit">Submit</syn-button>
        </form>
      `);
      const button = form.querySelector('syn-button')!;
      const radioGroup = form.querySelector<SynRadioGroup>('syn-radio-group')!;
      const submitHandler = sinon.spy((event: SubmitEvent) => event.preventDefault());

      // Submitting the form after setting custom validity should not trigger the handler
      radioGroup.setCustomValidity('Invalid selection');
      form.addEventListener('submit', submitHandler);
      button.click();

      await aTimeout(100);

      expect(submitHandler).to.not.have.been.called;
    });
  });
});

describe('when resetting a form', () => {
  it('should reset the element to its initial value', async () => {
    const form = await fixture<HTMLFormElement>(html`
      <form>
        <syn-radio-group value="1">
          <syn-radio value="1"></syn-radio>
          <syn-radio value="2"></syn-radio>
        </syn-radio-group>
        <syn-button type="reset">Reset</syn-button>
      </form>
    `);
    const button = form.querySelector('syn-button')!;
    const radioGroup = form.querySelector('syn-radio-group')!;
    radioGroup.value = '2';

    await radioGroup.updateComplete;
    setTimeout(() => button.click());

    await oneEvent(form, 'reset');
    await radioGroup.updateComplete;

    expect(radioGroup.value).to.equal('1');
  });
});

describe('when submitting a form', () => {
  it('should submit the correct value when a value is provided', async () => {
    const form = await fixture<HTMLFormElement>(html`
      <form>
        <syn-radio-group name="a" value="1">
          <syn-radio id="radio-1" value="1"></syn-radio>
          <syn-radio id="radio-2" value="2"></syn-radio>
          <syn-radio id="radio-3" value="3"></syn-radio>
        </syn-radio-group>
        <syn-button type="submit">Submit</syn-button>
      </form>
    `);
    const button = form.querySelector('syn-button')!;
    const radio = form.querySelectorAll('syn-radio')[1]!;
    const submitHandler = sinon.spy((event: SubmitEvent) => {
      formData = new FormData(form);

      event.preventDefault();
    });
    let formData: FormData;

    form.addEventListener('submit', submitHandler);
    radio.click();
    button.click();
    await waitUntil(() => submitHandler.calledOnce);

    expect(formData!.get('a')).to.equal('2');
  });

  it('should be present in form data when using the form attribute and located outside of a <form>', async () => {
    const el = await fixture<HTMLFormElement>(html`
      <div>
        <form id="f">
          <syn-button type="submit">Submit</syn-button>
        </form>
        <syn-radio-group form="f" name="a" value="1">
          <syn-radio id="radio-1" value="1"></syn-radio>
          <syn-radio id="radio-2" value="2"></syn-radio>
          <syn-radio id="radio-3" value="3"></syn-radio>
        </syn-radio-group>
      </div>
    `);
    const form = el.querySelector('form')!;
    const formData = new FormData(form);

    expect(formData.get('a')).to.equal('1');
  });
});

describe('when a size is applied', () => {
  it('should apply the same size to all radios', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group size="large">
        <syn-radio id="radio-1" value="1"></syn-radio>
        <syn-radio id="radio-2" value="2"></syn-radio>
      </syn-radio-group>
    `);
    const [radio1, radio2] = radioGroup.querySelectorAll('syn-radio')!;

    expect(radio1.size).to.equal('large');
    expect(radio2.size).to.equal('large');
  });

  it('should apply the same size to all radio buttons', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group size="large">
        <syn-radio-button id="radio-1" value="1"></syn-radio-button>
        <syn-radio-button id="radio-2" value="2"></syn-radio-button>
      </syn-radio-group>
    `);
    const [radio1, radio2] = radioGroup.querySelectorAll('syn-radio-button')!;

    expect(radio1.size).to.equal('large');
    expect(radio2.size).to.equal('large');
  });

  it('should update the size of all radio buttons when size changes', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group size="small">
        <syn-radio-button id="radio-1" value="1"></syn-radio-button>
        <syn-radio-button id="radio-2" value="2"></syn-radio-button>
      </syn-radio-group>
    `);
    const [radio1, radio2] = radioGroup.querySelectorAll('syn-radio-button')!;

    expect(radio1.size).to.equal('small');
    expect(radio2.size).to.equal('small');

    radioGroup.size = 'large';
    await radioGroup.updateComplete;

    expect(radio1.size).to.equal('large');
    expect(radio2.size).to.equal('large');
  });
});

describe('when handling focus', () => {
  const doAction = async (instance: SynRadioGroup, type: string) => {
    if (type === 'focus') {
      instance.focus();
      await instance.updateComplete;
      return;
    }

    const label = instance.shadowRoot!.querySelector<HTMLLabelElement>('#label')!;
    label.click();
    await instance.updateComplete;
  };

  // Tests for focus and label actions with radio buttons
  ['focus', 'label'].forEach(actionType => {
    describe(`when using ${actionType}`, () => {
      it('should do nothing if all elements are disabled', async () => {
        const el = await fixture<SynRadioGroup>(html`
          <syn-radio-group>
            <syn-radio id="radio-0" value="0" disabled></syn-radio>
            <syn-radio id="radio-1" value="1" disabled></syn-radio>
            <syn-radio id="radio-2" value="2" disabled></syn-radio>
            <syn-radio id="radio-3" value="3" disabled></syn-radio>
          </syn-radio-group>
        `);

        const validFocusHandler = sinon.spy();

        Array.from(el.querySelectorAll<SynRadio>('syn-radio')).forEach(radio =>
          radio.addEventListener('syn-focus', validFocusHandler)
        );

        expect(validFocusHandler).to.not.have.been.called;
        await doAction(el, actionType);
        expect(validFocusHandler).to.not.have.been.called;
      });

      it('should focus the first radio that is enabled when the group receives focus', async () => {
        const el = await fixture<SynRadioGroup>(html`
          <syn-radio-group>
            <syn-radio id="radio-0" value="0" disabled></syn-radio>
            <syn-radio id="radio-1" value="1"></syn-radio>
            <syn-radio id="radio-2" value="2"></syn-radio>
            <syn-radio id="radio-3" value="3"></syn-radio>
          </syn-radio-group>
        `);

        const invalidFocusHandler = sinon.spy();
        const validFocusHandler = sinon.spy();

        const disabledRadio = el.querySelector('#radio-0')!;
        const validRadio = el.querySelector('#radio-1')!;

        disabledRadio.addEventListener('syn-focus', invalidFocusHandler);
        validRadio.addEventListener('syn-focus', validFocusHandler);

        expect(invalidFocusHandler).to.not.have.been.called;
        expect(validFocusHandler).to.not.have.been.called;

        await doAction(el, actionType);

        expect(invalidFocusHandler).to.not.have.been.called;
        expect(validFocusHandler).to.have.been.called;
      });

      it('should focus the currently enabled radio when the group receives focus', async () => {
        const el = await fixture<SynRadioGroup>(html`
          <syn-radio-group value="2">
            <syn-radio id="radio-0" value="0" disabled></syn-radio>
            <syn-radio id="radio-1" value="1"></syn-radio>
            <syn-radio id="radio-2" value="2" checked></syn-radio>
            <syn-radio id="radio-3" value="3"></syn-radio>
          </syn-radio-group>
        `);

        const invalidFocusHandler = sinon.spy();
        const validFocusHandler = sinon.spy();

        const disabledRadio = el.querySelector('#radio-0')!;
        const validRadio = el.querySelector('#radio-2')!;

        disabledRadio.addEventListener('syn-focus', invalidFocusHandler);
        validRadio.addEventListener('syn-focus', validFocusHandler);

        expect(invalidFocusHandler).to.not.have.been.called;
        expect(validFocusHandler).to.not.have.been.called;

        await doAction(el, actionType);

        expect(invalidFocusHandler).to.not.have.been.called;
        expect(validFocusHandler).to.have.been.called;
      });
    });
  });
});

describe('when the value changes', () => {
  it('should emit syn-change when toggled with the arrow keys', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group>
        <syn-radio id="radio-1" value="1"></syn-radio>
        <syn-radio id="radio-2" value="2"></syn-radio>
      </syn-radio-group>
    `);
    const firstRadio = radioGroup.querySelector<SynRadio>('#radio-1')!;
    const changeHandler = sinon.spy();
    const inputHandler = sinon.spy();

    radioGroup.addEventListener('syn-change', changeHandler);
    radioGroup.addEventListener('syn-input', inputHandler);
    firstRadio.focus();
    await sendKeys({ press: 'ArrowRight' });
    await radioGroup.updateComplete;

    expect(changeHandler).to.have.been.calledOnce;
    expect(inputHandler).to.have.been.calledOnce;
    expect(radioGroup.value).to.equal('2');
  });

  it('should emit syn-change and syn-input when clicked', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group>
        <syn-radio id="radio-1" value="1"></syn-radio>
        <syn-radio id="radio-2" value="2"></syn-radio>
      </syn-radio-group>
    `);
    const radio = radioGroup.querySelector<SynRadio>('#radio-1')!;
    setTimeout(() => radio.click());
    const event = (await oneEvent(radioGroup, 'syn-change')) as SynChangeEvent;
    expect(event.target).to.equal(radioGroup);
    expect(radioGroup.value).to.equal('1');
  });

  it('should emit syn-change and syn-input when toggled with spacebar', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group>
        <syn-radio id="radio-1" value="1"></syn-radio>
        <syn-radio id="radio-2" value="2"></syn-radio>
      </syn-radio-group>
    `);
    const radio = radioGroup.querySelector<SynRadio>('#radio-1')!;
    radio.focus();
    setTimeout(() => sendKeys({ press: ' ' }));
    const event = (await oneEvent(radioGroup, 'syn-change')) as SynChangeEvent;
    expect(event.target).to.equal(radioGroup);
    expect(radioGroup.value).to.equal('1');
  });

  it('should not emit syn-change or syn-input when the value is changed programmatically', async () => {
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group value="1">
        <syn-radio id="radio-1" value="1"></syn-radio>
        <syn-radio id="radio-2" value="2"></syn-radio>
      </syn-radio-group>
    `);

    radioGroup.addEventListener('syn-change', () => expect.fail('syn-change should not be emitted'));
    radioGroup.addEventListener('syn-input', () => expect.fail('syn-input should not be emitted'));
    radioGroup.value = '2';
    await radioGroup.updateComplete;
  });

  it('should relatively position content to prevent visually hidden scroll bugs', async () => {
    //
    // See https://github.com/synergy-design-system/synergy/issues/1380
    //
    const radioGroup = await fixture<SynRadioGroup>(html`
      <syn-radio-group value="1">
        <syn-radio id="radio-1" value="1"></syn-radio>
      </syn-radio-group>
    `);

    const formControl = radioGroup.shadowRoot!.querySelector('.form-control')!;
    const visuallyHidden = radioGroup.shadowRoot!.querySelector('.visually-hidden')!;

    expect(getComputedStyle(formControl).position).to.equal('relative');
    expect(getComputedStyle(visuallyHidden).position).to.equal('absolute');
  });

  /**
   * @see https://github.com/synergy-design-system/synergy/issues/1361
   * This isn't really possible to test right now due to importing "synergy.js" which
   * auto-defines all of our components up front. This should be tested if we ever split
   * to non-auto-defining components and not auto-defining for tests.
   */
  it.skip('should sync up radios and radio buttons if defined after radio group', async () => {
    // customElements.define("syn-radio-group", SynRadioGroup)
    //
    // const radioGroup = await fixture<SynRadioGroup>(html`
    //   <syn-radio-group value="1">
    //     <syn-radio id="radio-1" value="1"></syn-radio>
    //     <syn-radio id="radio-2" value="2"></syn-radio>
    //   </syn-radio-group>
    // `);
    //
    // await aTimeout(1)
    //
    // customElements.define("syn-radio-button", SynRadioButton)
    //
    // expect(radioGroup.querySelector("syn-radio")?.getAttribute("aria-checked")).to.equal("false")
    //
    // await aTimeout(1)
    //
    // customElements.define("syn-radio", SynRadio)
    //
    // await aTimeout(1)
    //
    // expect(radioGroup.querySelector("syn-radio")?.getAttribute("aria-checked")).to.equal("true")
  });

  runFormControlBaseTests('syn-radio-group');
});
