// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY VENDORISM
// Removing this comment will prevent it from being managed by it.
// ---------------------------------------------------------------------

/* eslint-disable */
import SynRadioGroup from './radio-group.component.js';

export * from './radio-group.component.js';
export default SynRadioGroup;

SynRadioGroup.define('syn-radio-group');

declare global {
  interface HTMLElementTagNameMap {
    'syn-radio-group': SynRadioGroup;
  }
}
