import type { Preview } from "@storybook/web-components";

import { setCustomElementsManifest } from '@storybook/web-components';
import '../../tokens/src/docs.css';
import '../../tokens/src/_utility.css';
import '../../tokens/src/light.css';
import * as tokens from '@sick-design-system/tokens';

/**
 * This loads the custom elements manifest generated on run or on build time.
 */

async function loadCustomElements() {
  fetch('./custom-elements.json')
    .then(async () => {
      // Use dynamic manifest generated by Vite on runtime
      return await fetch('./custom-elements.json').then(res => { console.log(res); return res.json(); });
    })
    .then(async customElements => {
      setCustomElementsManifest(customElements);
    });

  console.log('Custom elements manifest loaded');
}

loadCustomElements();

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    badgesConfig: {
      needsHandoff: {
        styles: {
          backgroundColor: tokens.sdsColorAccent500,
          borderColor: tokens.sdsColorAccent600,
          color: tokens.sdsColorNeutral0,
        },
        title: 'Needs handoff',
      },
      v1: {
        styles: {
          backgroundColor: tokens.sdsColorPrimary500,
          borderColor: tokens.sdsColorNeutral800,
          color: tokens.sdsColorNeutral0,
        },
        title: 'v1.0.0'
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;
