/**
 * This file is auto-generated by figma-export.
 * Do not edit it manually.
 */
import figma, { html } from '@figma/code-connect/html';

// Synergy Web Component Connection for icon security_update_good
figma.connect('https://www.figma.com/design/bZFqk9urD3NlghGUKrkKCR?node-id=1616:2509', {
  example: ({
    name,
  }) => html`
    <syn-icon name=${name}></syn-icon>
  `,
  imports: [
    'import { SynIcon } from "@synergy-design-system/components";',
  ],
  links: [
    {
      name: 'Documentation',
      url: 'https://synergy-design-system.github.io/?path=/docs/components-syn-icon--docs',
    },
  ],
  props: {
    name: 'security_update_good',
  },
});
