// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY CUSTOM SHOELACE CLI
// Removing this comment will prevent it from being managed by the CLI.
// ---------------------------------------------------------------------

import SdsIcon from './icon.component.js';
export * from './icon.component.js';
export default SdsIcon;
SdsIcon.define('sds-icon');
