// ---------------------------------------------------------------------
// 🔒 AUTOGENERATED BY CUSTOM SHOELACE CLI
// Removing this comment will prevent it from being managed by the CLI.
// ---------------------------------------------------------------------


import './icon';
import type { Meta, StoryObj } from '@storybook/web-components';
import { html } from 'lit';
import docsTokens from '../../../../tokens/src/figma-tokens/_docs.json';
import { storybookDefaults, storybookHelpers, storybookTemplate } from '../../../.storybook/helper';
const { args, argTypes } = storybookDefaults('sds-icon');
const { overrideArgs } = storybookHelpers('sds-icon');
const { generateTemplate } = storybookTemplate('sds-icon');

const meta: Meta = {
  component: 'icon',
  args,
  argTypes,
  title: 'Components/sds-icon',
  parameters: {
    docs: {
      description: {
        component: docsTokens.components['icon'].description.value
      },
    }
  }
};
export default meta;

type Story = StoryObj;

export const Default = {
  render: (args: any) => {
    return generateTemplate({ args });
  },
  parameters: {
    docs: {
      description: {
        story: docsTokens.components['icon'].description.value
      }
    }
  }
} as Story;


/**
 * Icons inherit their color from the current text color. Thus, you can set the color property on the <sds-icon> element or an ancestor to change the color.
 */
export const Colors: Story = {
  render: () => html`<div style="color: #4a90e2;">
  <sds-icon name="exclamation-triangle"></sds-icon>
  <sds-icon name="archive"></sds-icon>
  <sds-icon name="battery-charging"></sds-icon>
  <sds-icon name="bell"></sds-icon>
</div>
<div style="color: #9013fe;">
  <sds-icon name="clock"></sds-icon>
  <sds-icon name="cloud"></sds-icon>
  <sds-icon name="download"></sds-icon>
  <sds-icon name="file-earmark"></sds-icon>
</div>
<div style="color: #417505;">
  <sds-icon name="flag"></sds-icon>
  <sds-icon name="heart"></sds-icon>
  <sds-icon name="image"></sds-icon>
  <sds-icon name="lightning"></sds-icon>
</div>
<div style="color: #f5a623;">
  <sds-icon name="mic"></sds-icon>
  <sds-icon name="search"></sds-icon>
  <sds-icon name="star"></sds-icon>
  <sds-icon name="trash"></sds-icon>
</div>`,
};

/**
 * Icons are sized relative to the current font size. To change their size, set the font-size property on the icon itself or on a parent element as shown below.
 */
export const Sizing: Story = {
  render: () => html`<div style="font-size: 32px;">
  <sds-icon name="exclamation-triangle"></sds-icon>
  <sds-icon name="archive"></sds-icon>
  <sds-icon name="battery-charging"></sds-icon>
  <sds-icon name="bell"></sds-icon>
  <sds-icon name="clock"></sds-icon>
  <sds-icon name="cloud"></sds-icon>
  <sds-icon name="download"></sds-icon>
  <sds-icon name="file-earmark"></sds-icon>
  <sds-icon name="flag"></sds-icon>
  <sds-icon name="heart"></sds-icon>
  <sds-icon name="image"></sds-icon>
  <sds-icon name="lightning"></sds-icon>
  <sds-icon name="mic"></sds-icon>
  <sds-icon name="search"></sds-icon>
  <sds-icon name="star"></sds-icon>
  <sds-icon name="trash"></sds-icon>
</div>`,
};

/**
 * For non-decorative icons, use the label attribute to announce it to assistive devices.
 */
export const Labels: Story = {
  render: () => html`<sds-icon name="star-fill" label="Add to favorites"></sds-icon>`,
};

/**
 * Custom icons can be loaded individually with the src attribute. Only SVGs on a local or CORS-enabled endpoint are supported. If you're using more than one custom icon, it might make sense to register a .
 */
export const CustomIcons: Story = {
  render: () => html`<sds-icon src="https://sick.style/assets/images/shoe.svg" style="font-size: 8rem;"></sds-icon>`,
};
