#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD)
CHANGED_FILES=$(git diff --cached --name-only)

PREFIX=$(node ./add-commit-prefix.js $BRANCH_NAME $CHANGED_FILES)

if [ -n "$PREFIX" ]; then
    sed -i.bak -e "1s/^/$PREFIX /" $1
fi
