name: Lint Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  changeset-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          with-build: 'false'

      - name: Run changeset linter
        id: lint
        run: |
          set -o pipefail
          OUTPUT=$(node packages/_private/release-utils/src/lint.js 2>&1 | tee lint-output.txt)
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find previous lint comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### Changeset Lint Status'

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Changeset Lint Status

            ```
            ${{ steps.lint.outputs.output }}
            ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
