name: Sync Figma variables to tokens
on:
  workflow_dispatch:
    inputs:
      figma_file_id:
        description: "This can either be a branch_id or the id for the main figma file"
        required: true
      branch_name:
        description: "The name for the branch, which should be created for the pull request"
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true pnpm i

      - name: Sync variables in Figma file to tokens
        run: pnpm -C ./packages/tokens fetch:figma && pnpm -C ./packages/tokens build:figma
        env:
          FIGMA_FILE_ID: ${{ github.event.inputs.figma_file_id }}
          # We need this exact naming of the FIGMA_TOKEN environment variable, as the @figma-export/cli dependency needs it
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update variables and styles from Figma
          title: "feat: ✨ Update tokens from Figma"
          body: "Update tokens from Figma from figma branch id ${{ github.event.inputs.figma_file_id }}"
          branch: ${{ github.event.inputs.branch_name }}
